---
# name: ansible-collection-meta
# file: playbooks/docs.yml

- name: "Generate contributing markdown for role {{ meta_role_name }}"
  hosts: "{{ target | default('all') }}"
  become: false
  gather_facts: false
  tasks:
    - name: "Generate CONTRIBUTING.md file from template"
      ansible.builtin.template:
        src: 'CONTRIBUTING.md.j2'
        dest: "{{ ansible_host }}/CONTRIBUTING.md"
        mode: "0644"
