---
# play: ansible-collection-meta
# file: playbooks/meta.yml

- name: "Play: generate meta/main.yml for roles inventory"
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: "Ensure that role and meta directory exist"
      ansible.builtin.file:
        path: "{{ ansible_chroot_dir }}/meta"
        state: directory
        mode: "0755"

    - name: "Install ansible-lint"
      ansible.builtin.pip:
        name: ansible-lint
        state: present
        extra_args: "--user --upgrade"

    - name: "Generate meta/main.yml for role {{ meta_role_name }}"
      ansible.builtin.template:
        src: "main.yml.j2"
        dest: "{{ ansible_chroot_dir }}/meta/main.yml"
        mode: "0755"
        validate: "ansible-lint --strict %s"
