---
# name: ansible-collection-meta
# file: playbooks/docs.yml

- name: "Generate readme markdown for role {{ meta_role_name }}"
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Generate README.md file from template"
      ansible.builtin.template:
        src: 'README.md.j2'
        dest: "{{ ansible_host }}/README.md"
        mode: "0644"
